/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/E3n8MEA2mLk
 */
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"

export function Table() {
  return (
    <div className="dark bg-black">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead className="w-[200px] text-white">Title</TableHead>
            <TableHead className="text-white">Author</TableHead>
            <TableHead className="text-white">Date Created</TableHead>
            <TableHead className="text-white">Connections</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          <TableRow>
            <TableCell className="font-bold text-white">Sapiens: A Brief History of Humankind</TableCell>
            <TableCell className="text-white">Yuval Noah Harari</TableCell>
            <TableCell className="text-white">2023-05-01</TableCell>
            <TableCell className="text-white">230</TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="font-bold text-white">The Alchemist</TableCell>
            <TableCell className="text-white">Paulo Coelho</TableCell>
            <TableCell className="text-white">2023-05-01</TableCell>
            <TableCell className="text-white">198</TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="font-bold text-white">Atomic Habits</TableCell>
            <TableCell className="text-white">James Clear</TableCell>
            <TableCell className="text-white">2023-05-01</TableCell>
            <TableCell className="text-white">176</TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="font-bold text-white">Thinking, Fast and Slow</TableCell>
            <TableCell className="text-white">Daniel Kahneman</TableCell>
            <TableCell className="text-white">2023-05-01</TableCell>
            <TableCell className="text-white">154</TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="font-bold text-white">The Lean Startup</TableCell>
            <TableCell className="text-white">Eric Ries</TableCell>
            <TableCell className="text-white">2023-05-01</TableCell>
            <TableCell className="text-white">142</TableCell>
          </TableRow>
        </TableBody>
      </Table>
    </div>
  )
}
