/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/DiV2VQkEJ5G
 */
import { Checkbox } from "@/components/ui/checkbox"
import { Badge } from "@/components/ui/badge"

export function TaskTable() {
  return (
    <div className="max-w-sm mx-auto my-10">
      <ul className="space-y-4">
        <li className="flex items-start space-x-3">
          <Checkbox id="task-1" />
          <div className="flex-1">
            <p className="font-semibold">Borrow Sarah's travel guide</p>
            <p className="text-sm text-gray-500">Vacation in Rome</p>
          </div>
          <Badge variant="secondary">today</Badge>
        </li>
        <li className="flex items-start space-x-3">
          <Checkbox id="task-2" />
          <div className="flex-1">
            <p className="font-semibold">Finish expense report</p>
            <p className="text-sm text-gray-500">Work</p>
          </div>
        </li>
        <li className="flex items-start space-x-3">
          <Checkbox id="task-3" />
          <div className="flex-1">
            <p className="font-semibold">Review quarterly data with Olivia</p>
            <p className="text-sm text-gray-500">Prepare Presentation</p>
          </div>
        </li>
        <li className="flex items-start space-x-3">
          <Checkbox id="task-4" />
          <div className="flex-1">
            <p className="font-semibold">Organize catering</p>
            <p className="text-sm text-gray-500">Work</p>
          </div>
        </li>
        <li className="flex items-start space-x-3">
          <Checkbox id="task-5" />
          <div className="flex-1">
            <p className="font-semibold">Get car inspected</p>
            <p className="text-sm text-gray-500">Family</p>
          </div>
        </li>
      </ul>
    </div>
  )
}
